# Generating dataset

In [45]:
# importing libraries
import pandas as pd
import matplotlib.pyplot as plt

In [46]:
# reading sample data
df = pd.read_csv('data/weekly hours studied vs marks.csv')
print('Shape of DataFrame :',df.shape)
df.head(10)

Shape of DataFrame : (100, 2)

   Hours  Marks
0     40     98
1     37     40
2     28     68
3     12     33
4     15     80
5     33     80
6     24     63
7     39     99
8     17     42
9     22     50

In [47]:
print(df.dtypes)
print(df.isnull().sum())

Hours    int64
Marks    int64
dtype: object
Hours    0
Marks    0
dtype: int64

In [48]:
df.describe()

            Hours       Marks
count  100.000000  100.000000
mean    20.780000   51.880000
std     11.136055   27.006651
min      0.000000    2.000000
25%     11.750000   30.000000
50%     20.500000   50.000000
75%     30.000000   74.500000
max     40.000000  100.000000

In [49]:
print('correlation :', df['Hours'].corr(df['Marks']))

correlation : 0.8476642071709332

In [ ]:
from sklearn.model_selection import train_test_split

X = df[['Hours']].values   # keep as 2D array (150, 1)
y = df['Marks'].values             # 1D array (150,)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

In [51]:
from sklearn.model_selection import train_test_split

X = df[['Hours']].values
y = df['Marks'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(80, 1) (20, 1) (80,) (20,)

# Gradient Descent Algorithm

In [65]:
#initialising parameters
w = 0.0 # weight of hours studied
b = 0.0 # bias 
alpha = 0.0001 # learning rate
epochs = 100 # number of iterations
costs = [] 

def predict(X, w, b):
    ypred = X * w + b
    return ypred.flatten()

y_pred = predict(X_train, w, b)
print(y_pred[:5])

[0. 0. 0. 0. 0.]

In [68]:
def compute_cost(y_train, y_pred):
    n = len(y_train)
    cost = (1/(n)) * sum((y_pred - y_train)**2)

    return cost
print("Cost:", compute_cost(y_train, y))

Cost: 3340.5750000000003

In [ ]:
def computegradient(X_train, y_train, y_pred):
    n = len(y_train)
    dw = (1/n) * sum((y_pred - y_train) * X_train.flatten())
    db = (1/n) * sum(y_pred - y_train)

    return dw, db

dw, db = computegradient(X_train, y_train, y_pred)
print("dw:", dw)
print("db:", db)

dw: -1301.9250000000002
db: -51.425000000000004